-- 022_marketplace_orders.sql
--
-- SLICE A — marketplace ordering. The first WRITE a person with no workshop
-- affiliation performs in this product. 021 let a stranger BROWSE; this lets a
-- signed-in customer BUY, direct from the supplier, which is the owner's stated
-- model: "user deal direct with supplier and payment in app payment process,
-- delivery is by delivery systems of the supplier."
--
-- ⚠️ THE RLS PREDICATE HERE IS NOT THE TENANT ONE, AND THAT IS THE WHOLE
-- DESIGN DECISION OF THIS MIGRATION. Every tenant-owned table in this
-- repository scopes on `app.tenant_id`. An order has no tenant: the buyer is a
-- vehicle owner who may belong to no organization at all, and the seller is a
-- `catalogue.suppliers` row which 021 deliberately defined as having "no
-- tenant, no users, no job cards". Scoping orders by tenant would either
-- invent a tenant for every private buyer or leave the table unprotected.
--
-- So an order is OWNED BY ITS BUYER, and the policy keys on
-- `identity.current_user_id()`. That function returns NULL when no user
-- context is set — measured, not assumed — so an anonymous visitor to the
-- public marketplace matches no row and the table fails closed, exactly as the
-- tenant tables do for a request with no tenant.
--
-- ⚠️ WHAT THIS MIGRATION DELIBERATELY DOES NOT CONTAIN — read before adding it.
--
-- 1. NO SUPPLIER-SIDE VISIBILITY POLICY. The handover asks for a supplier order
--    inbox. It cannot be built yet and faking it would be worse than saying so:
--    `catalogue.suppliers` has no `identity.users` link, no organization and no
--    membership, by explicit design in 021. There is therefore no subject a
--    supplier policy could key on — a supplier cannot sign in at all. The
--    schema below is shaped so that adding one later is additive: the order
--    header carries `supplier_id`, so the future policy is one CREATE POLICY
--    against whatever links a supplier to a user, and no column moves.
--
-- 2. NO PAYMENT PROVIDER, AND NO DEFAULT THAT IMPLIES ONE. `payment_method` is
--    NULLABLE WITH NO DEFAULT on purpose. In-app payment needs a provider, and
--    choosing one is a spend decision that belongs to the owner alone
--    (CLAUDE.md §1; ADR-015 bring-your-own-connection). This migration records
--    that a payment was or was not taken and how the tenant says it was taken.
--    It names no provider, integrates with none, and must not be "completed" by
--    adding one. The record is built so the flow is testable meanwhile.
--
-- 3. NO COURIER INTEGRATION AND NO INVENTED TRACKING STATES. Delivery is the
--    supplier's own system. We store the status the supplier REPORTS and a
--    free-text tracking reference. Modelling states we cannot observe would
--    produce a progress bar that lies.
--
-- ⚠️ CONSTRAINT ORDERING. A foreign key can only cite a unique constraint that
-- ALREADY EXISTS at the point the FK is declared — the trap that bit 014, 016
-- and 020. Each table below sits above the table that references it.

BEGIN;

-- ---------------------------------------------------------------------------
-- Issue 4 from the 2026-07-30 handover: the currency default was wrong.
-- ---------------------------------------------------------------------------
-- `catalogue.parts.currency` defaulted to 'GBP' while the product prices in
-- GHS. Nothing is wrong in the data today ONLY because the seed script sets
-- currency explicitly on every row — i.e. the defect is entirely latent, and
-- the first row inserted by a supplier UI without an explicit currency would
-- have silently been priced in the wrong one.
--
-- 021 is already applied and therefore CHECKSUMMED; editing it would fail the
-- ledger. The fix belongs in the next number, which is this one.
ALTER TABLE catalogue.parts ALTER COLUMN currency SET DEFAULT 'GHS';

-- ---------------------------------------------------------------------------
-- Orders — one order per SUPPLIER, not one per basket.
-- ---------------------------------------------------------------------------
-- A basket spanning three suppliers becomes three orders. That is not a
-- simplification, it follows from the owner's model: the customer deals direct
-- with each supplier and each supplier delivers with its own system, so there
-- is no single party who could own a combined order, fulfil it, or be paid for
-- it. A combined order would need a platform intermediary the product does not
-- have and the zero-cost rule does not permit.
CREATE TABLE catalogue.orders (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human reference the customer quotes to the supplier. Unique across the
  -- platform; generated by the service, not the database, so the format can
  -- change without a migration.
  order_number        TEXT NOT NULL,

  -- The buyer. A global `identity.users` row — NOT tenant-scoped, because a
  -- vehicle owner buying a filter belongs to no workshop.
  -- RESTRICT: a user with order history cannot be hard-deleted out from under
  -- their own financial record.
  buyer_user_id       UUID NOT NULL REFERENCES identity.users(id) ON DELETE RESTRICT,

  supplier_id         UUID NOT NULL REFERENCES catalogue.suppliers(id) ON DELETE RESTRICT,

  -- SNAPSHOT of the supplier's name at order time. The FK gives us the live
  -- row; this gives us what the customer actually agreed to buy from. A
  -- supplier rename must not silently rewrite a placed order.
  supplier_name       TEXT NOT NULL,

  -- ⚠️ STATUS IS A LIFECYCLE, NOT A DELIVERY TRACKER. Every value here is one
  -- the platform or the supplier can actually assert. There is no
  -- "out_for_delivery" or "at_local_depot" because nothing in this system can
  -- observe either, and a state we cannot set is a state that gets stuck.
  status              TEXT NOT NULL DEFAULT 'placed',

  -- Currency SNAPSHOT for the whole order. Denormalised from the lines on
  -- purpose: the total is meaningless without it, and a report that joins to
  -- `parts` to find the currency would read TODAY's currency for LAST year's
  -- order.
  currency            TEXT NOT NULL,

  -- Money SNAPSHOT. Same precision as `catalogue.parts.price` — numeric(14,2),
  -- never a float. A totals column that disagrees with the sum of its lines is
  -- a reconciliation bug, so `ck_order_total_non_negative` is the floor and the
  -- service is what keeps them equal.
  subtotal            NUMERIC(14,2) NOT NULL,
  delivery_fee        NUMERIC(14,2) NOT NULL DEFAULT 0,
  total               NUMERIC(14,2) NOT NULL,

  -- Where it goes. Free text, because Ghanaian addressing is not a postcode
  -- grid and a structured address form would reject real addresses.
  delivery_recipient  TEXT NOT NULL,
  delivery_phone      TEXT NOT NULL,
  delivery_address    TEXT NOT NULL,

  -- What the SUPPLIER reports, in the supplier's own words. Not parsed, not
  -- validated against a carrier, not turned into a progress bar.
  delivery_tracking_reference TEXT,
  delivery_notes      TEXT,

  -- ⚠️ PAYMENT: A RECORD, NOT AN INTEGRATION. See the header. NULL means
  -- nobody has said how this was paid — the honest state for an order placed
  -- before any payment mechanism exists. There is deliberately NO DEFAULT: a
  -- default would assert a payment method that was never chosen.
  payment_status      TEXT NOT NULL DEFAULT 'unpaid',
  payment_method      TEXT,
  payment_reference   TEXT,

  -- Why it was cancelled, when it was. A cancellation with no reason is an
  -- argument with a customer nobody can settle.
  cancelled_reason    TEXT,

  placed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_order_number UNIQUE (order_number),

  CONSTRAINT ck_order_status CHECK (
    status IN ('placed', 'confirmed', 'dispatched', 'delivered', 'cancelled')
  ),
  CONSTRAINT ck_order_payment_status CHECK (
    payment_status IN ('unpaid', 'paid', 'refunded')
  ),
  -- Currency is an ISO-4217 alpha code. Shape only — the list of codes the
  -- product actually supports is a service decision, not a schema one.
  CONSTRAINT ck_order_currency_shape CHECK (currency ~ '^[A-Z]{3}$'),

  CONSTRAINT ck_order_amounts_non_negative CHECK (
    subtotal >= 0 AND delivery_fee >= 0 AND total >= 0
  ),

  -- A cancelled order must say why; a live one must not carry a stale reason
  -- from a cancellation that was undone. Both directions, because only
  -- constraining one leaves the other free to be wrong.
  CONSTRAINT ck_order_cancelled_reason CHECK (
    (status = 'cancelled' AND cancelled_reason IS NOT NULL)
    OR (status <> 'cancelled' AND cancelled_reason IS NULL)
  )
);

-- ---------------------------------------------------------------------------
-- Order lines — the price the customer agreed, frozen.
-- ---------------------------------------------------------------------------
-- ⚠️ EVERY DISPLAY FIELD HERE IS A SNAPSHOT, AND THE FK IS NOT THE SOURCE OF
-- TRUTH FOR ANY OF THEM. The same rule `quotations` follows. If this table
-- joined to `catalogue.parts` to render an order, then re-pricing a part would
-- retroactively change what a customer was charged last month, and unpublishing
-- one would make a delivered order render as blank rows.
CREATE TABLE catalogue.order_lines (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  order_id      UUID NOT NULL REFERENCES catalogue.orders(id) ON DELETE CASCADE,

  -- Kept so "buy again" and analytics can find the live part. RESTRICT because
  -- an ordered part must remain resolvable; unpublishing is how a part leaves
  -- the marketplace, not deletion.
  part_id       UUID NOT NULL REFERENCES catalogue.parts(id) ON DELETE RESTRICT,

  -- SNAPSHOTS.
  part_name     TEXT NOT NULL,
  part_brand    TEXT,

  quantity      INTEGER NOT NULL,
  unit_price    NUMERIC(14,2) NOT NULL,
  currency      TEXT NOT NULL,
  line_total    NUMERIC(14,2) NOT NULL,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_order_line_quantity CHECK (quantity > 0),
  CONSTRAINT ck_order_line_amounts CHECK (unit_price >= 0 AND line_total >= 0),
  CONSTRAINT ck_order_line_currency_shape CHECK (currency ~ '^[A-Z]{3}$'),

  -- The arithmetic the customer can check. Enforced here because a line total
  -- that disagrees with quantity x unit price is the single most damaging
  -- silent defect this table can carry.
  CONSTRAINT ck_order_line_total_is_consistent CHECK (
    line_total = ROUND(unit_price * quantity, 2)
  )
);

-- ---------------------------------------------------------------------------
-- Order events — append-only.
-- ---------------------------------------------------------------------------
-- CLAUDE.md: approvals, payments and audit events are append-only; corrections
-- are new rows. This is the order's history and the only account of who changed
-- what, so it is the one table here that must never be rewritten.
CREATE TABLE catalogue.order_events (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id       UUID NOT NULL REFERENCES catalogue.orders(id) ON DELETE CASCADE,

  event_type     TEXT NOT NULL,

  -- Who did it. NULLABLE because not every event has a human author — a
  -- supplier-reported delivery update arrives without a platform user, and
  -- recording a false actor is worse than recording none.
  actor_user_id  UUID REFERENCES identity.users(id) ON DELETE RESTRICT,

  -- Free-text description. Not a schema, because the events this table must
  -- absorb are not all known yet and a rigid payload would be migrated monthly.
  detail         TEXT,

  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ck_order_event_type CHECK (
    event_type IN (
      'placed', 'confirmed', 'dispatched', 'delivered', 'cancelled',
      'payment_recorded', 'payment_refunded', 'tracking_updated', 'note_added'
    )
  )
);

-- ---------------------------------------------------------------------------
-- Indexes.
-- ---------------------------------------------------------------------------
-- "My orders", newest first — the only list screen a buyer has.
CREATE INDEX idx_orders_buyer        ON catalogue.orders (buyer_user_id, placed_at DESC);
-- The supplier inbox this migration does not yet expose. Created now because
-- the query shape is known and an index is cheaper than a later migration.
CREATE INDEX idx_orders_supplier     ON catalogue.orders (supplier_id, status, placed_at DESC);
CREATE INDEX idx_orders_status       ON catalogue.orders (status);
CREATE INDEX idx_order_lines_order   ON catalogue.order_lines (order_id);
CREATE INDEX idx_order_lines_part    ON catalogue.order_lines (part_id);
CREATE INDEX idx_order_events_order  ON catalogue.order_events (order_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- RLS.
-- ---------------------------------------------------------------------------
-- FORCE as well as ENABLE. ENABLE alone exempts the table OWNER, and migrations
-- run as the owner here — so a policy without FORCE is one psql session away
-- from being decorative. Measured after applying (`t | t`), never read off this
-- file.
ALTER TABLE catalogue.orders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogue.orders       FORCE  ROW LEVEL SECURITY;
ALTER TABLE catalogue.order_lines  ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogue.order_lines  FORCE  ROW LEVEL SECURITY;
ALTER TABLE catalogue.order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalogue.order_events FORCE  ROW LEVEL SECURITY;

-- The buyer, and nobody else without a policy of their own.
--
-- ⚠️ SEPARATE `FOR SELECT` AND `FOR INSERT` RATHER THAN ONE `FOR ALL`, and the
-- reason is the trap the Solar enterprise module hit: Postgres reuses a
-- policy's USING expression as its WITH CHECK for INSERT unless a WITH CHECK is
-- given. Written as `FOR ALL USING (...)` this would still work here — but only
-- by accident, because buyer_user_id happens to be set before the row exists.
-- Spelling both out means the INSERT rule is stated rather than inherited.
--
-- No UPDATE policy for the buyer: a placed order is not editable by the person
-- who placed it. Cancellation is a service operation that writes a status and
-- an event, and it runs under the admin path until the supplier side exists.
CREATE POLICY buyer_read ON catalogue.orders
  FOR SELECT USING (buyer_user_id = identity.current_user_id());
CREATE POLICY buyer_insert ON catalogue.orders
  FOR INSERT WITH CHECK (buyer_user_id = identity.current_user_id());

-- A line is visible exactly when ITS ORDER is. Written as a subquery rather
-- than a copied buyer_user_id column so the two can never disagree — a
-- denormalised owner here would be a second place to forget.
CREATE POLICY buyer_read ON catalogue.order_lines
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM catalogue.orders o
      WHERE o.id = order_id AND o.buyer_user_id = identity.current_user_id()
    )
  );
CREATE POLICY buyer_insert ON catalogue.order_lines
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM catalogue.orders o
      WHERE o.id = order_id AND o.buyer_user_id = identity.current_user_id()
    )
  );

CREATE POLICY buyer_read ON catalogue.order_events
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM catalogue.orders o
      WHERE o.id = order_id AND o.buyer_user_id = identity.current_user_id()
    )
  );
CREATE POLICY buyer_insert ON catalogue.order_events
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM catalogue.orders o
      WHERE o.id = order_id AND o.buyer_user_id = identity.current_user_id()
    )
  );

-- Platform admin, same convention as 021. FOR ALL, and permissive policies OR
-- together, so this is what lets support read and correct an order.
CREATE POLICY admin_all ON catalogue.orders
  FOR ALL USING (identity.current_role_name() = 'admin')
  WITH CHECK (identity.current_role_name() = 'admin');
CREATE POLICY admin_all ON catalogue.order_lines
  FOR ALL USING (identity.current_role_name() = 'admin')
  WITH CHECK (identity.current_role_name() = 'admin');
CREATE POLICY admin_all ON catalogue.order_events
  FOR ALL USING (identity.current_role_name() = 'admin')
  WITH CHECK (identity.current_role_name() = 'admin');

-- ---------------------------------------------------------------------------
-- Grants.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON catalogue.orders       TO autoworkshop_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON catalogue.order_lines  TO autoworkshop_app;
GRANT SELECT, INSERT                 ON catalogue.order_events TO autoworkshop_app;

-- ⚠️ THE REVOKE IS THE LINE THAT ACTUALLY MAKES IT APPEND-ONLY.
-- `ALTER DEFAULT PRIVILEGES` in this database already grants the full set to
-- `autoworkshop_app` at CREATE TABLE time, so the narrower GRANT above does NOT
-- subtract anything — it only fails to add what was already there. Without the
-- next two lines `order_events` would be silently rewritable and the GRANT
-- would read as though it were not. Same reasoning as 008.
--
-- Orders and lines keep DELETE only because `ON DELETE CASCADE` from a
-- cancelled-and-purged order needs it; a DELETE of a live order is refused by
-- the service, not by this grant.
REVOKE UPDATE, DELETE ON catalogue.order_events FROM autoworkshop_app;

COMMIT;
