-- 042 — finance: invoices, payments, receipts, refunds, credit notes
--
-- ══════════════════════════════════════════════════════════════════════════
-- SLICE 3 of docs/00-project/COMPLETION_PLAN.md — THE BACK OF THE WORKFLOW
-- ══════════════════════════════════════════════════════════════════════════
--
-- Today a job reaches quality control and STOPS. There is no invoice, so no job
-- can be closed for money and no vehicle can be released against a payment. The
-- plan calls this the highest business value in it, and that is not a
-- description of the schema — it is a description of a workshop that currently
-- cannot get paid through this product.
--
-- Built on `repair.quotations`, which already carries currency, labour rate, tax
-- rate and priced lines. An invoice is what the customer is ASKED to pay; the
-- quotation is what they AGREED to pay.
--
-- ══════════════════════════════════════════════════════════════════════════
-- 🔴 APPEND-ONLY, AND THIS ONE IS NOT A DEFAULT BEING FOLLOWED
-- ══════════════════════════════════════════════════════════════════════════
--
-- CLAUDE.md: "Approvals, payments, warranty decisions and audit events are
-- append-only." Every table here is a financial record, and the rule is
-- enforced in THREE places because any one of them alone has failed before:
--
--   · GRANTs withhold DELETE — and the REVOKE is not redundant, because 006's
--     ALTER DEFAULT PRIVILEGES hands UPDATE/DELETE to every new table in the
--     schema. 008 learned that expensively: an append-only table that silently
--     was not.
--   · triggers refuse the rewrite, firing on UPDATE **and** DELETE. "A rule
--     enforced on UPDATE and nowhere else" has been the defect twice here
--     (QC 030, variations 032) — a direct DELETE walked past a guard that read
--     correct.
--   · a settled invoice refuses edits to anything that changes what is owed.
--
-- Correcting a settled invoice is a CREDIT NOTE, never an edit. That is not
-- bureaucracy: an invoice a customer has already been shown, and possibly paid
-- against, is a record of what they were told. Changing it retrospectively
-- means the receipt in their hand no longer matches the system.
--
-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️ NO CARD PAYMENT, AND THE SCREENS MUST KEEP SAYING SO
-- ══════════════════════════════════════════════════════════════════════════
--
-- ADR-012 forbids a paid dependency, and every card processor is one. So a
-- payment here is RECORDED, not TAKEN: somebody at the desk marks that cash,
-- a transfer or a cheque arrived. `payment_method` has no `card_online` value
-- on purpose — a value the product cannot honour would be a promise the screen
-- makes and the workshop cannot keep.
--
-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️ MONEY IS numeric(14,2), NOT AN INTEGER OF MINOR UNITS
-- ══════════════════════════════════════════════════════════════════════════
--
-- Matching `repair.quotations` and `quotation_lines` exactly. A second money
-- representation in the same database is how a total that agrees on one screen
-- disagrees on the next, and the invoice is derived from the quotation — the
-- conversion is the bug. Totals are GENERATED by the database for the same
-- reason the quotation's are: an application-written total is free to disagree
-- with its own inputs.

BEGIN;

CREATE SCHEMA IF NOT EXISTS finance;
GRANT USAGE ON SCHEMA finance TO autoworkshop_app;

-- ── invoices ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS finance.invoices (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    job_card_id      uuid NOT NULL,
    -- What the customer agreed to. Nullable, because a workshop occasionally
    -- invoices work that never had a formal quotation (a walk-in oil change),
    -- and refusing that would push it back onto paper.
    quotation_id     uuid,
    customer_id      uuid REFERENCES core.customers(id) ON DELETE RESTRICT,

    -- Human-facing, unique per organisation, allocated by the service.
    invoice_number   TEXT NOT NULL CHECK (length(btrim(invoice_number)) > 0),

    status           TEXT NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft', 'issued', 'part_paid', 'paid',
                                       'void')),

    currency         TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    tax_rate_percent numeric(5,2) NOT NULL DEFAULT 0
                     CHECK (tax_rate_percent >= 0 AND tax_rate_percent <= 100),

    -- ⚠️ SNAPSHOT TOTALS, written once at ISSUE from the lines below and never
    -- recomputed on read. An issued invoice must say the same thing next year
    -- as it did on the day, even if a line's rounding rule or a tax rate later
    -- changes. `finance.recompute_invoice_totals` fills these while the invoice
    -- is still a draft, and the trigger freezes them at issue.
    net_total        numeric(14,2) NOT NULL DEFAULT 0 CHECK (net_total >= 0),
    tax_total        numeric(14,2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    gross_total      numeric(14,2) NOT NULL DEFAULT 0 CHECK (gross_total >= 0),

    notes            TEXT,
    void_reason      TEXT,

    issued_at        timestamptz,
    due_at           timestamptz,
    settled_at       timestamptz,

    created_by       uuid,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_by       uuid,
    updated_at       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_invoice_number UNIQUE (organization_id, invoice_number),
    -- An issued invoice must say WHEN. A draft must not claim to have been.
    CONSTRAINT chk_invoice_issued
        CHECK ((status = 'draft') = (issued_at IS NULL)),
    CONSTRAINT chk_invoice_void_reason
        CHECK (status <> 'void' OR void_reason IS NOT NULL),
    CONSTRAINT chk_invoice_settled
        CHECK ((status = 'paid') = (settled_at IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_invoice_tenant ON finance.invoices (tenant_id);
CREATE INDEX IF NOT EXISTS idx_invoice_tenant_status
    ON finance.invoices (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_invoice_tenant_created
    ON finance.invoices (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_job_card
    ON finance.invoices (tenant_id, job_card_id);
-- The query the outstanding-balances screen runs.
CREATE INDEX IF NOT EXISTS idx_invoice_unpaid
    ON finance.invoices (tenant_id, organization_id, due_at)
    WHERE status IN ('issued', 'part_paid');

ALTER TABLE finance.invoices DROP CONSTRAINT IF EXISTS uq_invoice_id_tenant;
ALTER TABLE finance.invoices ADD CONSTRAINT uq_invoice_id_tenant UNIQUE (id, tenant_id);

-- ── invoice lines ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS finance.invoice_lines (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    invoice_id       uuid NOT NULL,
    position         integer NOT NULL,

    -- The same vocabulary as `repair.quotation_lines`, deliberately. An invoice
    -- line is usually a quotation line that was actually done, and a second
    -- vocabulary would make the two impossible to reconcile.
    line_kind        TEXT NOT NULL CHECK (line_kind IN (
        'labour', 'part', 'consumable', 'external_service', 'other_charge')),

    -- Where this charge came from, so a customer asking "what is this?" can
    -- always be answered. Nullable: a line may be added by hand.
    quotation_line_id uuid,

    description      TEXT NOT NULL CHECK (length(btrim(description)) > 0),
    quantity         numeric(12,3) NOT NULL CHECK (quantity > 0),
    unit             TEXT,
    unit_price       numeric(14,2) NOT NULL CHECK (unit_price >= 0),

    -- ⚠️ COMPUTED BY THE DATABASE, same width and same rounding as the
    -- quotation's. An application-written line total is free to disagree with
    -- its own inputs.
    line_total       numeric(14,2)
                     GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,

    recorded_by      uuid,
    recorded_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_line_invoice_scope
        FOREIGN KEY (invoice_id, tenant_id) REFERENCES finance.invoices (id, tenant_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_invoice_line_invoice
    ON finance.invoice_lines (invoice_id, position);
CREATE INDEX IF NOT EXISTS idx_invoice_line_tenant
    ON finance.invoice_lines (tenant_id);

-- ── payments ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS finance.payments (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    invoice_id       uuid NOT NULL,

    amount           numeric(14,2) NOT NULL CHECK (amount > 0),
    currency         TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),

    -- ⚠️ NO `card_online`. ADR-012 forbids a paid processor, so this product
    -- RECORDS a payment rather than taking one. A method the workshop cannot
    -- honour would be a promise the screen makes and the desk cannot keep.
    payment_method   TEXT NOT NULL CHECK (payment_method IN (
        'cash', 'bank_transfer', 'cheque', 'mobile_money', 'card_terminal',
        'credit_note', 'other')),

    -- The workshop's own reference: a transfer id, a cheque number, a till slip.
    reference        TEXT,
    notes            TEXT,

    received_by      uuid REFERENCES identity.users(id) ON DELETE SET NULL,
    received_at      timestamptz NOT NULL DEFAULT now(),
    created_at       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_payment_invoice_scope
        FOREIGN KEY (invoice_id, tenant_id) REFERENCES finance.invoices (id, tenant_id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_payment_invoice ON finance.payments (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payment_tenant ON finance.payments (tenant_id);
CREATE INDEX IF NOT EXISTS idx_payment_tenant_created
    ON finance.payments (tenant_id, received_at DESC);

ALTER TABLE finance.payments DROP CONSTRAINT IF EXISTS uq_payment_id_tenant;
ALTER TABLE finance.payments ADD CONSTRAINT uq_payment_id_tenant UNIQUE (id, tenant_id);

-- ── receipts ────────────────────────────────────────────────────────────────
--
-- One per payment, and the customer's copy. A SEPARATE row rather than a flag
-- on the payment because a receipt has its own number, its own issue time and
-- its own reprint history — and because "was a receipt given" is a question a
-- workshop is asked.

CREATE TABLE IF NOT EXISTS finance.receipts (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    payment_id       uuid NOT NULL,
    receipt_number   TEXT NOT NULL CHECK (length(btrim(receipt_number)) > 0),

    issued_by        uuid REFERENCES identity.users(id) ON DELETE SET NULL,
    issued_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_receipt_number UNIQUE (organization_id, receipt_number),
    -- One receipt per payment. A second would be a reprint, which is a printing
    -- act rather than a new financial record.
    CONSTRAINT uq_receipt_payment UNIQUE (payment_id),
    CONSTRAINT fk_receipt_payment_scope
        FOREIGN KEY (payment_id, tenant_id) REFERENCES finance.payments (id, tenant_id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_receipt_tenant ON finance.receipts (tenant_id);
CREATE INDEX IF NOT EXISTS idx_receipt_tenant_created
    ON finance.receipts (tenant_id, issued_at DESC);

-- ── credit notes ────────────────────────────────────────────────────────────
--
-- How a settled invoice is corrected. See the header: an invoice the customer
-- has been shown is a record of what they were told, so it is never edited.

CREATE TABLE IF NOT EXISTS finance.credit_notes (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    invoice_id       uuid NOT NULL,
    credit_number    TEXT NOT NULL CHECK (length(btrim(credit_number)) > 0),

    amount           numeric(14,2) NOT NULL CHECK (amount > 0),
    currency         TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    reason           TEXT NOT NULL CHECK (length(btrim(reason)) > 0),

    issued_by        uuid REFERENCES identity.users(id) ON DELETE SET NULL,
    issued_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_credit_number UNIQUE (organization_id, credit_number),
    CONSTRAINT fk_credit_invoice_scope
        FOREIGN KEY (invoice_id, tenant_id) REFERENCES finance.invoices (id, tenant_id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_credit_tenant ON finance.credit_notes (tenant_id);
CREATE INDEX IF NOT EXISTS idx_credit_invoice ON finance.credit_notes (invoice_id);

-- ── refunds ─────────────────────────────────────────────────────────────────
--
-- Money going back OUT, against a payment that came in. Distinct from a credit
-- note: a credit note reduces what is OWED, a refund returns what was PAID.
-- Conflating them is how a workshop's books stop balancing.

CREATE TABLE IF NOT EXISTS finance.refunds (
    id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id        uuid NOT NULL REFERENCES identity.tenants(id) ON DELETE RESTRICT,
    organization_id  uuid NOT NULL REFERENCES identity.organizations(id) ON DELETE CASCADE,

    payment_id       uuid NOT NULL,
    amount           numeric(14,2) NOT NULL CHECK (amount > 0),
    currency         TEXT NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    reason           TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
    refund_method    TEXT NOT NULL CHECK (refund_method IN (
        'cash', 'bank_transfer', 'cheque', 'mobile_money', 'card_terminal', 'other')),

    issued_by        uuid REFERENCES identity.users(id) ON DELETE SET NULL,
    issued_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_refund_payment_scope
        FOREIGN KEY (payment_id, tenant_id) REFERENCES finance.payments (id, tenant_id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_refund_tenant ON finance.refunds (tenant_id);
CREATE INDEX IF NOT EXISTS idx_refund_payment ON finance.refunds (payment_id);
CREATE INDEX IF NOT EXISTS idx_refund_tenant_created
    ON finance.refunds (tenant_id, issued_at DESC);

-- ── a refund can never exceed what was actually paid ────────────────────────
--
-- ⚠️ A CHECK CONSTRAINT CANNOT EXPRESS THIS — it spans rows. Without it a
-- workshop could refund GHS 500 against a GHS 100 payment, twice, and nothing
-- would object until somebody counted the till.

CREATE OR REPLACE FUNCTION finance.reject_over_refund()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    paid      numeric(14,2);
    refunded  numeric(14,2);
BEGIN
    SELECT amount INTO paid FROM finance.payments WHERE id = NEW.payment_id;
    SELECT COALESCE(sum(amount), 0) INTO refunded
      FROM finance.refunds
     WHERE payment_id = NEW.payment_id AND id <> NEW.id;

    IF refunded + NEW.amount > paid THEN
        RAISE EXCEPTION
            'refunding % would take the total refunded on this payment to %, '
            'which is more than the % that was paid',
            NEW.amount, refunded + NEW.amount, paid
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_refund_limit ON finance.refunds;
CREATE TRIGGER trg_refund_limit
    BEFORE INSERT ON finance.refunds
    FOR EACH ROW
    EXECUTE FUNCTION finance.reject_over_refund();

-- ── the append-only guards ──────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION finance.reject_financial_rewrite()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- ⚠️ FIRES ON DELETE TOO. A guard that only watches UPDATE has been the
    -- defect twice in this repository.
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            '%.% is append-only: a financial record that can be deleted is not a record',
            TG_TABLE_SCHEMA, TG_TABLE_NAME
            USING ERRCODE = 'check_violation';
    END IF;
    RAISE EXCEPTION
        '%.% is append-only: correct it with a credit note or a refund, never an edit',
        TG_TABLE_SCHEMA, TG_TABLE_NAME
        USING ERRCODE = 'check_violation';
END;
$$;

-- Payments, receipts, credit notes and refunds are IMMUTABLE ONCE WRITTEN.
-- There is no legitimate edit to any of them: a mistaken payment is reversed by
-- a refund, a mistaken invoice by a credit note.
DROP TRIGGER IF EXISTS trg_payment_immutable ON finance.payments;
CREATE TRIGGER trg_payment_immutable
    BEFORE UPDATE OR DELETE ON finance.payments
    FOR EACH ROW EXECUTE FUNCTION finance.reject_financial_rewrite();

DROP TRIGGER IF EXISTS trg_receipt_immutable ON finance.receipts;
CREATE TRIGGER trg_receipt_immutable
    BEFORE UPDATE OR DELETE ON finance.receipts
    FOR EACH ROW EXECUTE FUNCTION finance.reject_financial_rewrite();

DROP TRIGGER IF EXISTS trg_credit_immutable ON finance.credit_notes;
CREATE TRIGGER trg_credit_immutable
    BEFORE UPDATE OR DELETE ON finance.credit_notes
    FOR EACH ROW EXECUTE FUNCTION finance.reject_financial_rewrite();

DROP TRIGGER IF EXISTS trg_refund_immutable ON finance.refunds;
CREATE TRIGGER trg_refund_immutable
    BEFORE UPDATE OR DELETE ON finance.refunds
    FOR EACH ROW EXECUTE FUNCTION finance.reject_financial_rewrite();

-- An invoice is different: it has a DRAFT life before anyone sees it, and its
-- status must be able to advance as money arrives. What it may never do is
-- change what is OWED after it has been issued.
CREATE OR REPLACE FUNCTION finance.reject_issued_invoice_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'finance.invoices is append-only: void the invoice with a reason instead'
            USING ERRCODE = 'check_violation';
    END IF;

    IF OLD.status <> 'draft' THEN
        IF NEW.net_total   IS DISTINCT FROM OLD.net_total
           OR NEW.tax_total   IS DISTINCT FROM OLD.tax_total
           OR NEW.gross_total IS DISTINCT FROM OLD.gross_total
           OR NEW.currency    IS DISTINCT FROM OLD.currency
           OR NEW.tax_rate_percent IS DISTINCT FROM OLD.tax_rate_percent
           OR NEW.invoice_number IS DISTINCT FROM OLD.invoice_number
           OR NEW.job_card_id IS DISTINCT FROM OLD.job_card_id
           OR NEW.issued_at   IS DISTINCT FROM OLD.issued_at THEN
            RAISE EXCEPTION
                'invoice % has been issued: what it says is owed cannot change. '
                'Issue a credit note, or void it with a reason.', OLD.invoice_number
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_invoice_issued ON finance.invoices;
CREATE TRIGGER trg_invoice_issued
    BEFORE UPDATE OR DELETE ON finance.invoices
    FOR EACH ROW EXECUTE FUNCTION finance.reject_issued_invoice_change();

-- And its LINES are frozen at issue for the same reason — otherwise the totals
-- are protected while the thing they are a total OF is not.
CREATE OR REPLACE FUNCTION finance.reject_issued_line_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    invoice_status TEXT;
    target uuid;
BEGIN
    target := CASE WHEN TG_OP = 'DELETE' THEN OLD.invoice_id ELSE NEW.invoice_id END;
    SELECT status INTO invoice_status FROM finance.invoices WHERE id = target;

    IF invoice_status IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION
            'this invoice has been issued: its lines are what the customer was shown '
            'and cannot be changed. Issue a credit note instead.'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

-- ⚠️ INSERT AS WELL AS UPDATE AND DELETE. Adding a line to an already-issued
-- invoice increases what is owed just as surely as editing one — and an INSERT
-- is exactly the statement a guard written for UPDATE would miss. That is the
-- QC 030 / variations 032 defect, asked of this trigger before shipping it.
DROP TRIGGER IF EXISTS trg_invoice_line_frozen ON finance.invoice_lines;
CREATE TRIGGER trg_invoice_line_frozen
    BEFORE INSERT OR UPDATE OR DELETE ON finance.invoice_lines
    FOR EACH ROW EXECUTE FUNCTION finance.reject_issued_line_change();

-- ── row-level security ──────────────────────────────────────────────────────

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'finance.invoices', 'finance.invoice_lines', 'finance.payments',
        'finance.receipts', 'finance.credit_notes', 'finance.refunds'
    ] LOOP
        EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('ALTER TABLE %s FORCE  ROW LEVEL SECURITY', t);

        EXECUTE format('DROP POLICY IF EXISTS %I ON %s', 'tenant_select', t);
        EXECUTE format(
            'CREATE POLICY %I ON %s FOR SELECT USING '
            '(identity.is_platform_admin() OR tenant_id = identity.current_tenant_id())',
            'tenant_select', t);

        EXECUTE format('DROP POLICY IF EXISTS %I ON %s', 'tenant_insert', t);
        EXECUTE format(
            'CREATE POLICY %I ON %s FOR INSERT WITH CHECK '
            '(identity.is_platform_admin() OR tenant_id = identity.current_tenant_id())',
            'tenant_insert', t);

        EXECUTE format('DROP POLICY IF EXISTS %I ON %s', 'tenant_update', t);
        EXECUTE format(
            'CREATE POLICY %I ON %s FOR UPDATE USING '
            '(identity.is_platform_admin() OR tenant_id = identity.current_tenant_id()) '
            'WITH CHECK '
            '(identity.is_platform_admin() OR tenant_id = identity.current_tenant_id())',
            'tenant_update', t);
    END LOOP;
END $$;

-- ── grants ──────────────────────────────────────────────────────────────────
--
-- ⚠️ NO DELETE ANYWHERE, and the REVOKE is what makes that true — 006's
-- ALTER DEFAULT PRIVILEGES grants UPDATE/DELETE on every new table in the
-- schema, so omitting DELETE from a GRANT leaves it in place.
--
-- UPDATE is granted only where a status legitimately advances: invoices (draft
-- -> issued -> part_paid -> paid) and their lines while still draft. The
-- immutable tables get INSERT and SELECT only, so the trigger is a second line
-- of defence rather than the only one.

GRANT SELECT, INSERT, UPDATE ON finance.invoices      TO autoworkshop_app;
GRANT SELECT, INSERT, UPDATE ON finance.invoice_lines TO autoworkshop_app;
GRANT SELECT, INSERT         ON finance.payments      TO autoworkshop_app;
GRANT SELECT, INSERT         ON finance.receipts      TO autoworkshop_app;
GRANT SELECT, INSERT         ON finance.credit_notes  TO autoworkshop_app;
GRANT SELECT, INSERT         ON finance.refunds       TO autoworkshop_app;

REVOKE DELETE ON finance.invoices      FROM autoworkshop_app;
REVOKE DELETE ON finance.invoice_lines FROM autoworkshop_app;
REVOKE DELETE, UPDATE ON finance.payments     FROM autoworkshop_app;
REVOKE DELETE, UPDATE ON finance.receipts     FROM autoworkshop_app;
REVOKE DELETE, UPDATE ON finance.credit_notes FROM autoworkshop_app;
REVOKE DELETE, UPDATE ON finance.refunds      FROM autoworkshop_app;

COMMIT;
