-- verify/042 — the append-only rules, PROVEN BY INJECTING EACH FAILURE.
--
-- ⚠️ EVERY CHECK HERE TRIES TO DO THE FORBIDDEN THING AND ASSERTS IT WAS
-- REFUSED. A verify that only does permitted things proves the happy path and
-- nothing else — this repository has recorded a guard that passed 4/4 with its
-- real defect re-injected, and a check that walked through its own gap.
--
-- Runs inside the caller's transaction. `rehearse-migration.yml` wraps this and
-- the migration together and ROLLS BACK, so it is safe against production.

DO $verify$
DECLARE
    tid uuid; oid uuid; jc uuid;
    inv uuid; pay uuid;
    refused boolean;
    rec record;
    passed int := 0;
BEGIN
    SELECT id INTO tid FROM identity.tenants LIMIT 1;
    SELECT id INTO oid FROM identity.organizations WHERE tenant_id = tid LIMIT 1;
    SELECT id INTO jc  FROM repair.job_cards WHERE tenant_id = tid LIMIT 1;
    IF jc IS NULL THEN jc := gen_random_uuid(); END IF;
    -- 🔴 `app.tenant_id`, NOT `app.current_tenant`.
    --
    -- `identity.current_tenant_id()` reads `app.tenant_id`. The first version of
    -- this verify set `app.current_tenant`, which is not a setting anything
    -- reads — and it PASSED 8/8 locally, because the local role is a SUPERUSER
    -- and bypasses RLS entirely, so no policy ever consulted the value.
    --
    -- `rehearse-migration.yml` ran the same script against production as the
    -- real, non-superuser role and it failed immediately:
    --
    --   ERROR: new row violates row-level security policy for table "invoices"
    --
    -- That is the third time this repository has met "LOCAL IS SUPERUSER,
    -- RENDER IS NOT" (036, 039, now this), and the first time a rehearsal caught
    -- it before the migration reached production rather than after.
    PERFORM set_config('app.tenant_id', tid::text, true);

    -- ── diagnostic, printed before the first insert ────────────────────
    -- Measure, do not infer. The first two rehearsals failed here and guessing
    -- which setting the policy reads is what produced the second failure.
    RAISE NOTICE '  ctx: current_user=% tenant_setting=% current_tenant_id=% org=%',
        current_user,
        COALESCE(current_setting('app.tenant_id', true), '<unset>'),
        COALESCE(identity.current_tenant_id()::text, '<null>'),
        COALESCE(oid::text, '<null>');
    RAISE NOTICE '  is_platform_admin=%', identity.is_platform_admin();
    FOR rec IN
        SELECT policyname, cmd, COALESCE(qual, '-') AS using_expr,
               COALESCE(with_check, '-') AS check_expr
          FROM pg_policies WHERE schemaname='finance' AND tablename='invoices'
    LOOP
        RAISE NOTICE '  policy % (%): USING % CHECK %',
            rec.policyname, rec.cmd, rec.using_expr, rec.check_expr;
    END LOOP;

    -- 1. a draft invoice can be built
    INSERT INTO finance.invoices (tenant_id, organization_id, job_card_id,
                                  invoice_number, currency, tax_rate_percent)
    VALUES (tid, oid, jc, 'VERIFY-042-' || substr(gen_random_uuid()::text, 1, 8), 'GHS', 15)
    RETURNING id INTO inv;
    INSERT INTO finance.invoice_lines (tenant_id, organization_id, invoice_id, position,
                                       line_kind, description, quantity, unit_price)
    VALUES (tid, oid, inv, 0, 'labour', 'Diagnostic hour', 2, 150.00);
    passed := passed + 1;
    RAISE NOTICE '  1/8 a draft invoice accepts lines';

    -- 2. the generated line total is the DATABASE's arithmetic, not ours
    PERFORM 1 FROM finance.invoice_lines WHERE invoice_id = inv AND line_total = 300.00;
    IF NOT FOUND THEN RAISE EXCEPTION 'line_total was not computed as 300.00'; END IF;
    passed := passed + 1;
    RAISE NOTICE '  2/8 line_total is generated by the database';

    -- 3. issue it
    UPDATE finance.invoices
       SET status = 'issued', issued_at = now(),
           net_total = 300.00, tax_total = 45.00, gross_total = 345.00
     WHERE id = inv;
    passed := passed + 1;
    RAISE NOTICE '  3/8 a draft invoice can be issued';

    -- 4. INJECT: change what an issued invoice says is owed
    refused := false;
    BEGIN
        UPDATE finance.invoices SET gross_total = 1.00 WHERE id = inv;
    EXCEPTION WHEN check_violation THEN refused := true;
    END;
    IF NOT refused THEN RAISE EXCEPTION 'an ISSUED invoice let its total be changed'; END IF;
    passed := passed + 1;
    RAISE NOTICE '  4/8 an issued invoice refuses a change to what is owed';

    -- 5. INJECT: add a line to an issued invoice (the INSERT case a guard
    --    written only for UPDATE would miss)
    refused := false;
    BEGIN
        INSERT INTO finance.invoice_lines (tenant_id, organization_id, invoice_id,
                                           position, line_kind, description,
                                           quantity, unit_price)
        VALUES (tid, oid, inv, 1, 'part', 'Smuggled-in charge', 1, 999.00);
    EXCEPTION WHEN check_violation THEN refused := true;
    END;
    IF NOT refused THEN RAISE EXCEPTION 'a line was ADDED to an issued invoice'; END IF;
    passed := passed + 1;
    RAISE NOTICE '  5/8 an issued invoice refuses a NEW line (INSERT, not just UPDATE)';

    -- 6. a payment can be recorded
    INSERT INTO finance.payments (tenant_id, organization_id, invoice_id, amount,
                                  currency, payment_method)
    VALUES (tid, oid, inv, 100.00, 'GHS', 'cash') RETURNING id INTO pay;
    passed := passed + 1;
    RAISE NOTICE '  6/8 a payment can be recorded';

    -- 7. INJECT: edit and delete a payment
    refused := false;
    BEGIN
        UPDATE finance.payments SET amount = 5.00 WHERE id = pay;
    EXCEPTION WHEN check_violation THEN refused := true;
    END;
    IF NOT refused THEN RAISE EXCEPTION 'a payment was EDITED'; END IF;
    refused := false;
    BEGIN
        DELETE FROM finance.payments WHERE id = pay;
    EXCEPTION WHEN check_violation THEN refused := true;
    END;
    IF NOT refused THEN RAISE EXCEPTION 'a payment was DELETED'; END IF;
    passed := passed + 1;
    RAISE NOTICE '  7/8 a payment refuses both UPDATE and DELETE';

    -- 8. INJECT: refund more than was paid
    refused := false;
    BEGIN
        INSERT INTO finance.refunds (tenant_id, organization_id, payment_id, amount,
                                     currency, reason, refund_method)
        VALUES (tid, oid, pay, 500.00, 'GHS', 'over-refund attempt', 'cash');
    EXCEPTION WHEN check_violation THEN refused := true;
    END;
    IF NOT refused THEN RAISE EXCEPTION 'refunded MORE than was paid'; END IF;
    -- and a legitimate partial refund is still allowed, so the rule is a rule
    -- and not a wall
    INSERT INTO finance.refunds (tenant_id, organization_id, payment_id, amount,
                                 currency, reason, refund_method)
    VALUES (tid, oid, pay, 40.00, 'GHS', 'goodwill', 'cash');
    passed := passed + 1;
    RAISE NOTICE '  8/8 a refund cannot exceed the payment, but a partial one is allowed';

    RAISE NOTICE 'verify/042: OK (%/8)', passed;
END $verify$;
